apiVersion: v1
kind: Service
metadata:
  name: my-custom-app-service
  namespace: my-app-namespace
  labels:
    app: my-custom-app
spec:
  type: NodePort
  selector:
    app: my-custom-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
